name: gdg_gug_website
description: "GDG Gurugram University - Comprehensive platform for events, community, and networking"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  
  # Routing & Navigation
  go_router: ^14.0.2
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Firebase Services
  firebase_core: ^3.14.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
  
  # Authentication & Security
  google_sign_in: ^6.2.1
  crypto: ^3.0.5
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Enhancements
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  
  # Forms & Validation (using built-in Flutter forms for now)
  # flutter_form_builder: ^9.1.1
  # form_builder_validators: ^9.1.0
  
  # Media & Rich Content
  video_player: ^2.8.1
  flutter_markdown: ^0.6.18
  
  # Calendar & DateTime
  table_calendar: ^3.0.9
  
  # Animations
  flutter_animate: ^4.3.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/logos/
  #   - assets/animations/
  
  # fonts:
  #   - family: GoogleSans
  #     fonts:
  #       - asset: assets/fonts/GoogleSans-Regular.ttf
  #       - asset: assets/fonts/GoogleSans-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/GoogleSans-Medium.ttf
  #         weight: 500
