// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG7y6QjPx1qnTnRCauJNTZKHfs75LgbeY',
    appId: '1:139564775363:web:c159372d7bcd6c607b2f76',
    messagingSenderId: '139564775363',
    projectId: 'gdggug-5cfa2',
    authDomain: 'gdggug-5cfa2.firebaseapp.com',
    storageBucket: 'gdggug-5cfa2.firebasestorage.app',
    measurementId: 'G-2FRM2YDBXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmU5Bhz1wjuC4vTNa_TxtVWBIuJ-E-5c',
    appId: '1:139564775363:android:55f037d198dc60bf7b2f76',
    messagingSenderId: '139564775363',
    projectId: 'gdggug-5cfa2',
    storageBucket: 'gdggug-5cfa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLxFbqt9-la9DVa9R9dKxXFuLLNMLwys',
    appId: '1:139564775363:ios:5ac3b2d5b282ddcd7b2f76',
    messagingSenderId: '139564775363',
    projectId: 'gdggug-5cfa2',
    storageBucket: 'gdggug-5cfa2.firebasestorage.app',
    iosBundleId: 'com.example.gdgGugWebsite',
  );
}
